### PR TITLE
250 precursor fixes

### PR DESCRIPTION
**Pull request by james-nash**
Hi @e2tha-e,

I spotted another minor bug in your PR #293 - basically a dupe of the typo bug. I hope you don't mind, but I forked off your PR and did the fix. If you like, you can merge it into your repo before this goes back into patternlab-node.

While going through the open issues on patternlab-node, I also spotted issue #145 which will get fixed by your PR. I therefore added an additional test case to verify this. This is also included in this PR.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Excited to see this get in! Thanks to both of you for your work!

**Comment by james-nash** [comment]
Since @e2tha-e already fixed the typo bug and the `250-precursor` branch has now been merged into the upstream `dev`, this PR is now redundant so I'll close it.

@bmuenzenmeyer The only other thing in here was an extra test case that shows that issue #145 has also been fixed. If you'd like to incorporate that, ping me and I can provide it as a new PR directly off of `patternlab-node`.

**Comment by bmuenzenmeyer** [comment]
Hey @james-nash 

Thanks for the teamwork guys. 
I always welcome more tests :+1: if you have the time

**Comment by james-nash** [comment]
@bmuenzenmeyer Sure thing. I've just created PR #307 for the test. HTH

**Pull request closed without merging**
